item_types:
    ezlocation:
        name: item_types.ezlocation
        preview:
            template: '%netgen_content_browser.ezpublish.default_item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezpublish\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezpublish\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: '%netgen_content_browser.ezpublish.default_thumbnail_template%'
            type:
                name: columns.ezpublish.type
                value_provider: ezpublish\content_type
            visible:
                name: columns.ezpublish.visible
                value_provider: ezpublish\visible
            owner:
                name: columns.ezpublish.owner
                value_provider: ezpublish\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezpublish\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezpublish\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezpublish\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezpublish\section
        default_columns:
            - name
            - type
            - visible

    ezcontent:
        name: item_types.ezcontent
        preview:
            template: '%netgen_content_browser.ezpublish.default_item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezpublish\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezpublish\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: '%netgen_content_browser.ezpublish.default_thumbnail_template%'
            type:
                name: columns.ezpublish.type
                value_provider: ezpublish\content_type
            visible:
                name: columns.ezpublish.visible
                value_provider: ezpublish\visible
            owner:
                name: columns.ezpublish.owner
                value_provider: ezpublish\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezpublish\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezpublish\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezpublish\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezpublish\section
        default_columns:
            - name
            - type
            - visible
