parameters:
    netgen_content_browser.default.backend.ezlocation.location_content_types:
        - ng_frontpage
        - ng_category
        - ng_landing_page
        - ng_container
        - user_group
        - folder

    netgen_content_browser.default.backend.ezlocation.default_sections: [2, 43, 5]

services:
    # Backends

    netgen_content_browser.backend.ezlocation:
        class: Netgen\ContentBrowser\Backend\EzLocationBackend
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.translation_helper"
            - "@netgen_content_browser.config.ezlocation"
            - $backend.ezlocation.location_content_types;netgen_content_browser$
            - $backend.ezlocation.default_sections;netgen_content_browser$
        lazy: true
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            -  { name: netgen_content_browser.backend, item_type: ezlocation }

    netgen_content_browser.backend.ezcontent:
        class: Netgen\ContentBrowser\Backend\EzContentBackend
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.translation_helper"
            - "@netgen_content_browser.config.ezcontent"
            - $backend.ezlocation.location_content_types;netgen_content_browser$
            - $backend.ezlocation.default_sections;netgen_content_browser$
        lazy: true
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            -  { name: netgen_content_browser.backend, item_type: ezcontent }

    # Column value providers

    netgen_content_browser.column_value_provider.ezlocation.location_id:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\LocationId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\location_id }

    netgen_content_browser.column_value_provider.ezlocation.content_id:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\ContentId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\content_id }

    netgen_content_browser.column_value_provider.ezlocation.content_type:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\ContentType
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\content_type }

    netgen_content_browser.column_value_provider.ezlocation.modified:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Modified
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\modified }

    netgen_content_browser.column_value_provider.ezlocation.published:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Published
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\published }

    netgen_content_browser.column_value_provider.ezlocation.owner:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Owner
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\owner }

    netgen_content_browser.column_value_provider.ezlocation.priority:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Priority
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\priority }

    netgen_content_browser.column_value_provider.ezlocation.section:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Section
        public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\section }

    netgen_content_browser.column_value_provider.ezlocation.visible:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzLocation\Visible
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezlocation\visible }

    netgen_content_browser.column_value_provider.ezcontent.location_id:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\LocationId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\location_id }

    netgen_content_browser.column_value_provider.ezcontent.content_id:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\ContentId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\content_id }

    netgen_content_browser.column_value_provider.ezcontent.content_type:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\ContentType
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\content_type }

    netgen_content_browser.column_value_provider.ezcontent.modified:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Modified
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\modified }

    netgen_content_browser.column_value_provider.ezcontent.published:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Published
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\published }

    netgen_content_browser.column_value_provider.ezcontent.owner:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Owner
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\owner }

    netgen_content_browser.column_value_provider.ezcontent.priority:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Priority
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\priority }

    netgen_content_browser.column_value_provider.ezcontent.section:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Section
        public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\section }

    netgen_content_browser.column_value_provider.ezcontent.visible:
        class: Netgen\ContentBrowser\Item\ColumnProvider\ColumnValueProvider\EzContent\Visible
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezcontent\visible }
