item_types:
    eztags:
        name: item_types.eztags
        min_selected: 1
        max_selected: 0
        preview:
            template: '%netgen_content_browser.eztags.default_item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            tag_id:
                name: columns.eztags.tag_id
                value_provider: eztags\tag_id
            parent_tag_id:
                name: columns.eztags.parent_tag_id
                value_provider: eztags\parent_tag_id
            parent_tag:
                name: columns.eztags.parent_tag
                value_provider: eztags\parent_tag
            modified:
                name: columns.eztags.modified
                value_provider: eztags\modified
        default_columns:
            - name
            - parent_tag
            - modified
