services:
    netgen_content_browser.backend.eztags:
        class: Netgen\ContentBrowser\Ez\Backend\EzTagsBackend
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.translation_helper"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_content_browser.backend, item_type: eztags }

    netgen_content_browser.column_value_provider.eztags.tag_id:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzTags\TagId
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\tag_id }

    netgen_content_browser.column_value_provider.eztags.parent_tag_id:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzTags\ParentTagId
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\parent_tag_id }

    netgen_content_browser.column_value_provider.eztags.parent_tag:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzTags\ParentTag
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\parent_tag }

    netgen_content_browser.column_value_provider.eztags.modified:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzTags\Modified
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\modified }
