dist: trusty
sudo: false

language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"

matrix:
  include:
    -
      php: 7.1
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0" DEPS="low"
    -
      php: 7.2
      env: RUN_PHPSTAN="yes"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer require --no-update symfony/symfony:$SYMFONY_VERSION ; fi

  # PHPStan cannot be installed on Symfony 2.8
  - if [ "$SYMFONY_VERSION" = "~2.8.0" ] ; then composer remove --dev --no-update phpstan/phpstan phpstan/phpstan-phpunit ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi

notifications:
  email: false
  slack:
    secure: uD2TOci5W8PziIPUiHdUlUS+XViWgteL/IwLXq1pXS7LWuhr4b9bNeoNGnm2nhztVa5xF7WrsC+hczbGLyVjSR29Un02U4a96/qYwN9GL/eD7M6M/rcq1xhAZXzYDug0fQFVx2Q52V3Bzjo9ydAmw1Y92YtBi+rmwJFK/0Ysb2S7NQzVXJyQ0P7jP3oDAt4Xk9glX4p+e+BmJCDIPJpVKn6MNrowjKLlboD0dWmoAQEYl4yuWqO528lPzt81TffJfTg4RDFcN15m9VAnIsV7jzGao2nAalmDh95ttopjiie672pjbTazBOk7L+m/sGPsoh5GjZNqKkRXB+Vze22bkIyAhHFN2PurXXPWxX+/PAUbPcGDpWUdalczMDrXz3KDRabPkG1eVa2mrrqiPvqhcxOsi95NaT9uDHa/yUQgRXsVGunrVfXNW98htqS1T2OcsJlF7Zb7FZuoldrG71jVkvfNU14BO6OmWpaH7dhtYOWNGKyCrsaLKJskq2sluZVCuqpbyKIctD5UAAIheWxxZzLS8zz8bSDY5ETOdGx0G43tQ37TKaH8gVGHvWYMIOE2Q4V6HgcZIsGghL+LSBGBdLp3ihx+DLei/JW5c7b0LX+SAG60VlDKD8FHhCqylu/762fQ8Ry5sNQGtmRBSxCyb00vHo4GhTGauz2XuYhqdos=
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
