configs:
    ezcontent:
        min_selected: 1
        max_selected: 0
        template: 'NetgenContentBrowserBundle:ezpublish:item.html.twig'
        columns:
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezcontent\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezcontent\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: 'NetgenContentBrowserBundle:ezpublish/columns:thumbnail.html.twig'
            type:
                name: columns.ezpublish.type
                value_provider: ezcontent\content_type
            visibility:
                name: columns.ezpublish.visibility
                value_provider: ezcontent\visibility
            owner:
                name: columns.ezpublish.owner
                value_provider: ezcontent\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezcontent\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezcontent\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezcontent\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezcontent\section
        default_columns:
            - type
            - visible

    ezlocation:
        min_selected: 1
        max_selected: 1
        template: 'NetgenContentBrowserBundle:ezpublish:item.html.twig'
        columns:
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezlocation\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezlocation\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: 'NetgenContentBrowserBundle:ezpublish/columns:thumbnail.html.twig'
            type:
                name: columns.ezpublish.type
                value_provider: ezlocation\content_type
            visibility:
                name: columns.ezpublish.visibility
                value_provider: ezlocation\visibility
            owner:
                name: columns.ezpublish.owner
                value_provider: ezlocation\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezlocation\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezlocation\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezlocation\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezlocation\section
        default_columns:
            - type
            - visible
