configs:
    ezcontent:
        converter: netgen_content_browser.converter.ezcontent
        backend: netgen_content_browser.backend.ezcontent
        root_items: [2, 43, 5]
        min_selected: 1
        max_selected: 0
        default_limit: 25
        template: 'NetgenContentBrowserBundle:ezpublish:item.html.twig'
        types: []
        category_types:
            - ng_frontpage
            - ng_category
            - ng_landing_page
            - ng_category_page
            - ng_container
            - user_group
        columns:
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezpublish\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezpublish\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: 'NetgenContentBrowserBundle:ezpublish/columns:thumbnail.html.twig'
            type:
                name: columns.ezpublish.type
                value_provider: ezpublish\content_type
            visible:
                name: columns.ezpublish.visible
                value_provider: ezpublish\visible
            owner:
                name: columns.ezpublish.owner
                value_provider: ezpublish\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezpublish\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezpublish\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezpublish\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezpublish\section
        default_columns:
            - type
            - visible

    ezlocation:
        converter: netgen_content_browser.converter.ezlocation
        backend: netgen_content_browser.backend.ezlocation
        root_items: [2, 43, 5]
        min_selected: 1
        max_selected: 0
        default_limit: 25
        template: 'NetgenContentBrowserBundle:ezpublish:item.html.twig'
        types: []
        category_types:
            - ng_frontpage
            - ng_category
            - ng_landing_page
            - ng_category_page
            - ng_container
            - user_group
        columns:
            location_id:
                name: columns.ezpublish.location_id
                value_provider: ezpublish\location_id
            content_id:
                name: columns.ezpublish.content_id
                value_provider: ezpublish\content_id
            thumbnail:
                name: columns.ezpublish.thumbnail
                template: 'NetgenContentBrowserBundle:ezpublish/columns:thumbnail.html.twig'
            type:
                name: columns.ezpublish.type
                value_provider: ezpublish\content_type
            visible:
                name: columns.ezpublish.visible
                value_provider: ezpublish\visible
            owner:
                name: columns.ezpublish.owner
                value_provider: ezpublish\owner
            modified:
                name: columns.ezpublish.modified
                value_provider: ezpublish\modified
            published:
                name: columns.ezpublish.published
                value_provider: ezpublish\published
            priority:
                name: columns.ezpublish.priority
                value_provider: ezpublish\priority
            section:
                name: columns.ezpublish.section
                value_provider: ezpublish\section
        default_columns:
            - type
            - visible
