parameters:
    netgen_content_browser.backend.ezpublish.class: Netgen\Bundle\ContentBrowserBundle\Backend\EzPublishBackend

    netgen_content_browser.converter.ezcontent.class: Netgen\Bundle\ContentBrowserBundle\Item\Converter\EzContentItemConverter
    netgen_content_browser.converter.ezlocation.class: Netgen\Bundle\ContentBrowserBundle\Item\Converter\EzLocationItemConverter

    netgen_content_browser.config_loader.field_definition.class: Netgen\Bundle\ContentBrowserBundle\Config\FieldDefinition\ConfigLoader
    netgen_content_browser.config_loader.field_definition.ezobjectrelationlist.class: Netgen\Bundle\ContentBrowserBundle\Config\FieldDefinition\RelationListConfigLoader

services:
    # Backends

    netgen_content_browser.backend.ezpublish:
        class: "%netgen_content_browser.backend.ezpublish.class%"
        arguments:
            - "@ezpublish.api.service.search"
            - "@netgen_content_browser.current_config"

    # Converters

    netgen_content_browser.converter.ezlocation:
        class: "%netgen_content_browser.converter.ezlocation.class%"
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
            - "%netgen_content_browser.config.ezlocation%"

    netgen_content_browser.converter.ezcontent:
        class: "%netgen_content_browser.converter.ezcontent.class%"
        parent: netgen_content_browser.converter.ezlocation

    # Config loaders

    netgen_content_browser.config_loader.field_definition:
        class: "%netgen_content_browser.config_loader.field_definition.class%"
        arguments:
            - "@ezpublish.api.service.content_type"

    netgen_content_browser.config_loader.field_definition.ezobjectrelationlist:
        class: "%netgen_content_browser.config_loader.field_definition.ezobjectrelationlist.class%"
        parent: netgen_content_browser.config_loader.field_definition
        tags:
            - { name: netgen_content_browser.config_loader }
