configs:
    eztags:
        converter: netgen_content_browser.converter.eztags
        backend: netgen_content_browser.backend.eztags
        root_items: [0]
        min_selected: 1
        max_selected: 0
        default_limit: 25
        template: 'NetgenContentBrowserBundle:eztags:item.html.twig'
        types: []
        category_types: []
        columns:
            tag_id:
                name: columns.eztags.tag_id
                value_provider: eztags\tag_id
            parent_tag_id:
                name: columns.eztags.parent_tag_id
                value_provider: eztags\parent_tag_id
            parent_tag:
                name: columns.eztags.parent_tag
                value_provider: eztags\parent_tag
            modified:
                name: columns.eztags.modified
                value_provider: eztags\modified
        default_columns:
            - parent_tag
            - modified
