parameters:
    netgen_content_browser.backend.eztags.class: Netgen\Bundle\ContentBrowserBundle\Backend\EzTagsBackend
    netgen_content_browser.converter.eztags.class: Netgen\Bundle\ContentBrowserBundle\Item\Converter\EzTagsItemConverter
    netgen_content_browser.config_loader.field_definition.eztags.class: Netgen\Bundle\ContentBrowserBundle\Config\FieldDefinition\EzTagsConfigLoader

services:
    # Backends

    netgen_content_browser.backend.eztags:
        class: "%netgen_content_browser.backend.eztags.class%"
        arguments:
            - "@ezpublish.api.service.tags"
            - "@netgen_content_browser.current_config"
            - $languages$

    # Converters

    netgen_content_browser.converter.eztags:
        class: "%netgen_content_browser.converter.eztags.class%"
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish.translation_helper"

    # Config loaders

    netgen_content_browser.config_loader.field_definition.eztags:
        class: "%netgen_content_browser.config_loader.field_definition.eztags.class%"
        parent: netgen_content_browser.config_loader.field_definition
        tags:
            - { name: netgen_content_browser.config_loader }
