parameters:
    netgen_content_browser.backend.eztags.class: Netgen\Bundle\ContentBrowserBundle\Backend\EzTagsBackend

    netgen_content_browser.serializer.handler.eztags.class: Netgen\Bundle\ContentBrowserBundle\Item\Serializer\Handler\EzTagsSerializerHandler
    netgen_content_browser.template_value_provider.eztags.class: Netgen\Bundle\ContentBrowserBundle\Item\Renderer\TemplateValueProvider\EzTagsTemplateValueProvider

    netgen_content_browser.config_processor.field_definition.eztags.class: Netgen\Bundle\ContentBrowserBundle\Config\FieldDefinition\EzTagsConfigProcessor

    netgen_content_browser.column_value_provider.eztags.tag_id.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\EzTags\TagId
    netgen_content_browser.column_value_provider.eztags.parent_tag_id.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\EzTags\ParentTagId
    netgen_content_browser.column_value_provider.eztags.parent_tag.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\EzTags\ParentTag
    netgen_content_browser.column_value_provider.eztags.modified.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\EzTags\Modified

services:
    netgen_content_browser.backend.eztags:
        class: "%netgen_content_browser.backend.eztags.class%"
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish.translation_helper"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_content_browser.backend, value_type: eztags }

    netgen_content_browser.serializer.handler.eztags:
        class: "%netgen_content_browser.serializer.handler.eztags.class%"
        tags:
            - { name: netgen_content_browser.serializer.handler, value_type: eztags }

    netgen_content_browser.template_value_provider.eztags:
        class: "%netgen_content_browser.template_value_provider.eztags.class%"
        tags:
            - { name: netgen_content_browser.template_value_provider, value_type: eztags }

    netgen_content_browser.config_processor.field_definition.eztags:
        class: "%netgen_content_browser.config_processor.field_definition.eztags.class%"
        parent: netgen_content_browser.config_processor.field_definition
        tags:
            - { name: netgen_content_browser.config_processor }

    netgen_content_browser.column_value_provider.eztags.tag_id:
        class: "%netgen_content_browser.column_value_provider.eztags.tag_id.class%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\tag_id }

    netgen_content_browser.column_value_provider.eztags.parent_tag_id:
        class: "%netgen_content_browser.column_value_provider.eztags.parent_tag_id.class%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\parent_tag_id }

    netgen_content_browser.column_value_provider.eztags.parent_tag:
        class: "%netgen_content_browser.column_value_provider.eztags.parent_tag.class%"
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\parent_tag }

    netgen_content_browser.column_value_provider.eztags.modified:
        class: "%netgen_content_browser.column_value_provider.eztags.modified.class%"
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: eztags\modified }
