item_types:
    ibexa_location:
        name: item_types.ibexa_location
        preview:
            template: '%netgen_content_browser.ibexa.item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            location_id:
                name: columns.ibexa.location_id
                value_provider: ibexa\location_id
            content_id:
                name: columns.ibexa.content_id
                value_provider: ibexa\content_id
            thumbnail:
                name: columns.ibexa.thumbnail
                template: '%netgen_content_browser.ibexa.thumbnail_template%'
            type:
                name: columns.ibexa.type
                value_provider: ibexa\content_type
            visible:
                name: columns.ibexa.visible
                value_provider: ibexa\visible
            owner:
                name: columns.ibexa.owner
                value_provider: ibexa\owner
            modified:
                name: columns.ibexa.modified
                value_provider: ibexa\modified
            published:
                name: columns.ibexa.published
                value_provider: ibexa\published
            priority:
                name: columns.ibexa.priority
                value_provider: ibexa\priority
            section:
                name: columns.ibexa.section
                value_provider: ibexa\section
            object_state:
                name: columns.ibexa.object_state
                value_provider: ibexa\object_state
        default_columns:
            - name
            - type
            - visible

    ibexa_content:
        name: item_types.ibexa_content
        preview:
            template: '%netgen_content_browser.ibexa.item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            location_id:
                name: columns.ibexa.location_id
                value_provider: ibexa\location_id
            content_id:
                name: columns.ibexa.content_id
                value_provider: ibexa\content_id
            thumbnail:
                name: columns.ibexa.thumbnail
                template: '%netgen_content_browser.ibexa.thumbnail_template%'
            type:
                name: columns.ibexa.type
                value_provider: ibexa\content_type
            visible:
                name: columns.ibexa.visible
                value_provider: ibexa\visible
            owner:
                name: columns.ibexa.owner
                value_provider: ibexa\owner
            modified:
                name: columns.ibexa.modified
                value_provider: ibexa\modified
            published:
                name: columns.ibexa.published
                value_provider: ibexa\published
            priority:
                name: columns.ibexa.priority
                value_provider: ibexa\priority
            section:
                name: columns.ibexa.section
                value_provider: ibexa\section
            object_state:
                name: columns.ibexa.object_state
                value_provider: ibexa\object_state
        default_columns:
            - name
            - type
            - visible
