parameters:
    netgen_content_browser.default.backend.ezpublish.location_content_types:
        - folder
        - ng_category
        - ng_container
        - ng_frontpage
        - ng_landing_page
        - ng_topic
        - user_group

    netgen_content_browser.default.backend.ezpublish.default_sections: [2, 43, 5]

services:
    # Alias to eZ Platform search service, allowing for replacement
    # of search service with other implementations system wide

    netgen_content_browser.ezpublish.search_service:
        alias: ezpublish.api.service.search
        public: false

    # Backends

    netgen_content_browser.backend.ezlocation:
        class: Netgen\ContentBrowser\Ez\Backend\EzPublishBackend
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@netgen_content_browser.ezpublish.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@netgen_content_browser.config.ezlocation"
        lazy: true
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            -  { name: netgen_content_browser.backend, item_type: ezlocation }

    netgen_content_browser.backend.ezcontent:
        class: Netgen\ContentBrowser\Ez\Backend\EzPublishBackend
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@netgen_content_browser.ezpublish.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@netgen_content_browser.config.ezcontent"
        lazy: true
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            -  { name: netgen_content_browser.backend, item_type: ezcontent }

    # Config load events

    netgen_content_browser.event_listener.ezpublish.set_sections:
        class: Netgen\Bundle\ContentBrowserEzPlatformBundle\EventListener\EzPublish\SetSectionsListener
        # public: false
        arguments:
            - "@ezpublish.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    netgen_content_browser.event_listener.ezpublish.set_location_content_types:
        class: Netgen\Bundle\ContentBrowserEzPlatformBundle\EventListener\EzPublish\SetLocationContentTypesListener
        # public: false
        arguments:
            - "@ezpublish.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    # Column value providers

    netgen_content_browser.column_value_provider.ezpublish.location_id:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\LocationId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\location_id }

    netgen_content_browser.column_value_provider.ezpublish.content_id:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\ContentId
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\content_id }

    netgen_content_browser.column_value_provider.ezpublish.content_type:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\ContentType
        public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\content_type }

    netgen_content_browser.column_value_provider.ezpublish.modified:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Modified
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\modified }

    netgen_content_browser.column_value_provider.ezpublish.published:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Published
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\published }

    netgen_content_browser.column_value_provider.ezpublish.owner:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Owner
        public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\owner }

    netgen_content_browser.column_value_provider.ezpublish.priority:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Priority
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\priority }

    netgen_content_browser.column_value_provider.ezpublish.section:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Section
        public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\section }

    netgen_content_browser.column_value_provider.ezpublish.visible:
        class: Netgen\ContentBrowser\Ez\Item\ColumnProvider\ColumnValueProvider\EzPublish\Visible
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: ezpublish\visible }
